export const shadow = [
  { color: "red", opacity: 0.1 },
  { color: "red", opacity: 0.2 },
  { color: "red", opacity: 0.3 },
  { color: "red", opacity: 0.4 },
  { color: "red", opacity: 0.5 },
  { color: "red", opacity: 0.6 },
  { color: "red", opacity: 0.7 },
  { color: "red", opacity: 0.8 },
  { color: "red", opacity: 0.9 },
  { color: "red", opacity: 1 },

  { color: "orange", opacity: 0.1 },
  { color: "orange", opacity: 0.2 },
  { color: "orange", opacity: 0.3 },
  { color: "orange", opacity: 0.4 },
  { color: "orange", opacity: 0.5 },
  { color: "orange", opacity: 0.6 },
  { color: "orange", opacity: 0.7 },
  { color: "orange", opacity: 0.8 },
  { color: "orange", opacity: 0.9 },
  { color: "orange", opacity: 1 },

  { color: "Yellow", opacity: 0.1 },
  { color: "Yellow", opacity: 0.2 },
  { color: "Yellow", opacity: 0.3 },
  { color: "Yellow", opacity: 0.4 },
  { color: "Yellow", opacity: 0.5 },
  { color: "Yellow", opacity: 0.6 },
  { color: "Yellow", opacity: 0.7 },
  { color: "Yellow", opacity: 0.8 },
  { color: "Yellow", opacity: 0.9 },
  { color: "Yellow", opacity: 1 },

  { color: "Green", opacity: 0.1 },
  { color: "Green", opacity: 0.2 },
  { color: "Green", opacity: 0.3 },
  { color: "Green", opacity: 0.4 },
  { color: "Green", opacity: 0.5 },
  { color: "Green", opacity: 0.6 },
  { color: "Green", opacity: 0.7 },
  { color: "Green", opacity: 0.8 },
  { color: "Green", opacity: 0.9 },
  { color: "Green", opacity: 1 },

  { color: "Blue", opacity: 0.1 },
  { color: "Blue", opacity: 0.2 },
  { color: "Blue", opacity: 0.3 },
  { color: "Blue", opacity: 0.4 },
  { color: "Blue", opacity: 0.5 },
  { color: "Blue", opacity: 0.6 },
  { color: "Blue", opacity: 0.7 },
  { color: "Blue", opacity: 0.8 },
  { color: "Blue", opacity: 0.9 },
  { color: "Blue", opacity: 1 },

  { color: "Purple", opacity: 0.1 },
  { color: "Purple", opacity: 0.2 },
  { color: "Purple", opacity: 0.3 },
  { color: "Purple", opacity: 0.4 },
  { color: "Purple", opacity: 0.5 },
  { color: "Purple", opacity: 0.6 },
  { color: "Purple", opacity: 0.7 },
  { color: "Purple", opacity: 0.8 },
  { color: "Purple", opacity: 0.9 },
  { color: "Purple", opacity: 1 },

  { color: "Tomato", opacity: 0.1 },
  { color: "Tomato", opacity: 0.2 },
  { color: "Tomato", opacity: 0.3 },
  { color: "Tomato", opacity: 0.4 },
  { color: "Tomato", opacity: 0.5 },
  { color: "Tomato", opacity: 0.6 },
  { color: "Tomato", opacity: 0.7 },
  { color: "Tomato", opacity: 0.8 },
  { color: "Tomato", opacity: 0.9 },
  { color: "Tomato", opacity: 1 },

  { color: "Pink", opacity: 0.1 },
  { color: "Pink", opacity: 0.2 },
  { color: "Pink", opacity: 0.3 },
  { color: "Pink", opacity: 0.4 },
  { color: "Pink", opacity: 0.5 },
  { color: "Pink", opacity: 0.6 },
  { color: "Pink", opacity: 0.7 },
  { color: "Pink", opacity: 0.8 },
  { color: "Pink", opacity: 0.9 },
  { color: "Pink", opacity: 1 },

  { color: "Fuchsia", opacity: 0.1 },
  { color: "Fuchsia", opacity: 0.2 },
  { color: "Fuchsia", opacity: 0.3 },
  { color: "Fuchsia", opacity: 0.4 },
  { color: "Fuchsia", opacity: 0.5 },
  { color: "Fuchsia", opacity: 0.6 },
  { color: "Fuchsia", opacity: 0.7 },
  { color: "Fuchsia", opacity: 0.8 },
  { color: "Fuchsia", opacity: 0.9 },
  { color: "Fuchsia", opacity: 1 },

  { color: "Cyan", opacity: 0.1 },
  { color: "Cyan", opacity: 0.2 },
  { color: "Cyan", opacity: 0.3 },
  { color: "Cyan", opacity: 0.4 },
  { color: "Cyan", opacity: 0.5 },
  { color: "Cyan", opacity: 0.6 },
  { color: "Cyan", opacity: 0.7 },
  { color: "Cyan", opacity: 0.8 },
  { color: "Cyan", opacity: 0.9 },
  { color: "Cyan", opacity: 1 },

  { color: "Teal", opacity: 0.1 },
  { color: "Teal", opacity: 0.2 },
  { color: "Teal", opacity: 0.3 },
  { color: "Teal", opacity: 0.4 },
  { color: "Teal", opacity: 0.5 },
  { color: "Teal", opacity: 0.6 },
  { color: "Teal", opacity: 0.7 },
  { color: "Teal", opacity: 0.8 },
  { color: "Teal", opacity: 0.9 },
  { color: "Teal", opacity: 1 },

  { color: "Lime", opacity: 0.1 },
  { color: "Lime", opacity: 0.2 },
  { color: "Lime", opacity: 0.3 },
  { color: "Lime", opacity: 0.4 },
  { color: "Lime", opacity: 0.5 },
  { color: "Lime", opacity: 0.6 },
  { color: "Lime", opacity: 0.7 },
  { color: "Lime", opacity: 0.8 },
  { color: "Lime", opacity: 0.9 },
  { color: "Lime", opacity: 1 },

  { color: "Gray", opacity: 0.1 },
  { color: "Gray", opacity: 0.2 },
  { color: "Gray", opacity: 0.3 },
  { color: "Gray", opacity: 0.4 },
  { color: "Gray", opacity: 0.5 },
  { color: "Gray", opacity: 0.6 },
  { color: "Gray", opacity: 0.7 },
  { color: "Gray", opacity: 0.8 },
  { color: "Gray", opacity: 0.9 },
  { color: "Gray", opacity: 1 },

  { color: "Violet", opacity: 0.1 },
  { color: "Violet", opacity: 0.2 },
  { color: "Violet", opacity: 0.3 },
  { color: "Violet", opacity: 0.4 },
  { color: "Violet", opacity: 0.5 },
  { color: "Violet", opacity: 0.6 },
  { color: "Violet", opacity: 0.7 },
  { color: "Violet", opacity: 0.8 },
  { color: "Violet", opacity: 0.9 },
  { color: "Violet", opacity: 1 },

  { color: "aqua", opacity: 0.1 },
  { color: "aqua", opacity: 0.2 },
  { color: "aqua", opacity: 0.3 },
  { color: "aqua", opacity: 0.4 },
  { color: "aqua", opacity: 0.5 },
  { color: "aqua", opacity: 0.6 },
  { color: "aqua", opacity: 0.7 },
  { color: "aqua", opacity: 0.8 },
  { color: "aqua", opacity: 0.9 },
  { color: "aqua", opacity: 1 },

  { color: "navy", opacity: 0.1 },
  { color: "navy", opacity: 0.2 },
  { color: "navy", opacity: 0.3 },
  { color: "navy", opacity: 0.4 },
  { color: "navy", opacity: 0.5 },
  { color: "navy", opacity: 0.6 },
  { color: "navy", opacity: 0.7 },
  { color: "navy", opacity: 0.8 },
  { color: "navy", opacity: 0.9 },
  { color: "navy", opacity: 1 },
];
