export const routeTypes = {
  SHADOW_GENERATOR_VIEW: "SHADOW_GENERATOR_VIEW",
  SHADOW_VIEW: "SHADOW_VIEW",
  COLOR_GENERATOR_VIEW: "COLOR_GENERATOR_VIEW",
  COLOR_PALETTE_GENERATOR_VIEW: "COLOR_PALETTE_GENERATOR_VIEW",
  COLOR_HOME_VIEW: "COLOR_HOME_VIEW",
  COLOR_GENERATOR: "COLOR_GENERATOR",
  TEXT_GENERATOR_VIEW: "TEXT_GENERATOR_VIEW",
};
